name: Build Mojo Snap Plugin

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "shared/**"
      - "build.ps1"
      - ".github/workflows/build.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "shared/**"
      - "build.ps1"
      - ".github/workflows/build.yml"

jobs:
  build:
    name: Build Mojo Snap Plugin
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore src/MojoSnapPlugin.csproj

      - name: Build plugin assembly
        run: dotnet build src/MojoSnapPlugin.csproj -c Release -o dist/

      - name: Install Inno Setup
        run: choco install innosetup -y --no-progress

      - name: Build Setup Executable
        run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss'

      - name: Upload Releases
        uses: actions/upload-artifact@v4
        with:
          name: mojo-snap-releases
          path: |
            dist/MojoSnapPlugin.dll
            dist/MojoSnap_Setup.exe
